name: 2.4.7 Bookworm - Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 2.4.7/bookworm/**
      - config/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./2.4.7/bookworm/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: clickandmortar/magento:2.4.7-bookworm
